### PR TITLE
Update lint timeout

### PR DESCRIPTION
**Pull request by austinvalle**
🧹 🧹 🧹

### CODE REVIEW

**Review by bschaatsbergen — COMMENTED** [review]
Does it actually run longer than 5 minutes?

**Review by bschaatsbergen — APPROVED** [review]
LGTM! 🚀

**Review by bendbennett — APPROVED** [review]
LGTM 🚀

**Comment by austinvalle** [comment]
> Does it actually run longer than 5 minutes?

Very rarely the linter will get hung up, although not enough to be too much of a pain 🙂

**Pull request merged**
