### PR TITLE
Random String and Password Import

### PR DESCRIPTION
**Pull request by jahantech**
This PR enables import functionality for random string. Resource state changes are used to determine if the string generation criterias were met.

### CODE REVIEW

**Comment by crisp2u** [comment]
Looks good. Do you need help testing this ?

**Comment by jahantech** [comment]
I have performed tests with basic as well as special characters based strings. But if you have some spare time to run through some cases that would be great. In terms of unit testing, I can add a test for  updateStringResourceAttributes method if required.

**Comment by cursedcoder** [comment]
Looks good.

**Comment by cursedcoder** [comment]
So far works pretty good:
```
module.tcp.random_string.db_password: Importing from ID "PgYIYHschNVy0ZeroQMTcq1mEa6WOd"...
module.tcp.random_string.db_password: Import prepared!
  Prepared random_string for import
module.tcp.random_string.db_password: Refreshing state... [id=PgYIYHschNVy0ZeroQMTcq1mEa6WOd]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by paultyng** [comment]
@jahantech can you add import steps to the acceptance testing? Here is an example in AWS: https://github.com/terraform-providers/terraform-provider-aws/blob/98b8b848ca94031b20c3e626c9d40484e3af80de/aws/resource_aws_iot_topic_rule_test.go#L33-L37

**Comment by jahantech** [comment]
@paultyng  Thank you for providing the details. I have added the tests to my local branch, but they are not currently passing because my `updateStringResourceAttributes` function relies on `_, newMinClass := d.GetChange(charClassMin)` and when the tests are executed `d.GetChange(charClassMin)` always returns 0 changes. I will look into further to see how I can resolve this issue.

**Comment by paultyng** [comment]
For an import, your code only runs through the import and read functions, the config file is not referenced, so you have a few options:
- make `0` work somehow
- add the additional data to the import string in addition to the password/string itself
- ignore configuration/behavioral fields in the import test
Hard for me to say which is the appropriate choice, I'd have to dig in to the functionality a little more, but wanted to give you some ideas.

**Comment by jahantech** [comment]
@paultyng I would have to ignore all the fields as they are set to 0. In such case I have ImportStateVerify to false and the test now passes. Let me know if that is acceptable. Also I noticed the travis build is now failing on the master. My tests do pass locally.

**Comment by paultyng** [comment]
I reworked some of the code and import testing in #104, there were some other minor issues with the repo so cleaned those up as well (vendoring). For import testing, you should explicitly ignore anything that is only user entered and not determined by the read. Its possible though that this would let people import strings that don't satisfy the create criteria, but I think that's an acceptable situation if they already have an existing password or something they want to use.

**Pull request closed without merging**
